from OBD2.OBDFrames import OBDLiveDataPIDs

ACCELEROMETER_PORT = "/dev/tty.usbserial-110"
GPS_PORT = "/dev/tty.usbmodem1301"

SERVICE_UUID = "0000ffe0-0000-1000-8000-00805f9b34fb"
CHARACTERISTIC_UUID = "0000ffe1-0000-1000-8000-00805f9b34fb"
DEVICE_ADDRESS = '7190750E-043A-11A3-9560-D5FAAC66EEEA'

CHARACTERISTIC_HANDLE = 24
PRINT_TO_SCREEN = True
INITIAL_READINGS = [OBDLiveDataPIDs.MAP,
                    OBDLiveDataPIDs.IAT,
                    OBDLiveDataPIDs.RPM,
                    OBDLiveDataPIDs.SPEED,
                    OBDLiveDataPIDs.CALCULATED_ENGINE_LOAD]

UPDATE_CYCLE = [
    OBDLiveDataPIDs.MAP,
    OBDLiveDataPIDs.RPM,
    OBDLiveDataPIDs.CALCULATED_ENGINE_LOAD,
    OBDLiveDataPIDs.SPEED,
    OBDLiveDataPIDs.MAP,
    OBDLiveDataPIDs.RPM,
    OBDLiveDataPIDs.CALCULATED_ENGINE_LOAD,
    OBDLiveDataPIDs.MAP,
    OBDLiveDataPIDs.RPM,
    OBDLiveDataPIDs.CALCULATED_ENGINE_LOAD,
    OBDLiveDataPIDs.SPEED,
    OBDLiveDataPIDs.MAP,
    OBDLiveDataPIDs.RPM,
    OBDLiveDataPIDs.CALCULATED_ENGINE_LOAD,
    OBDLiveDataPIDs.MAP,
    OBDLiveDataPIDs.RPM,
    OBDLiveDataPIDs.CALCULATED_ENGINE_LOAD,
    OBDLiveDataPIDs.SPEED,
    OBDLiveDataPIDs.MAP,
    OBDLiveDataPIDs.RPM,
    OBDLiveDataPIDs.CALCULATED_ENGINE_LOAD,
    OBDLiveDataPIDs.IAT]

OUTPUT = './test-final.csv'

INTERVAL = 0.18

CORRECTION_COEFFICIENT = 1.1

OPEN_WEATHER_API_KEY = 'f0aaf2030e18f3c68b18247a66e8f04b'
